/* tslint:disable */
/* eslint-disable */
/**
 * 宠物寄养平台
 * 宠物寄养平台
 *
 * The version of the OpenAPI document: 1.0
 * Contact: 123456@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface BoardingOrderDto {
    /**
     * 笼位
     */
    'cageId'?: number;
    /**
     * 结束寄养时间
     */
    'endDate'?: string;
    /**
     * 订单状态: 1-待确认, 2-已预约(定金已付), 3-寄养中(已入托), 4-待结算, 5-已完成, 0-已取消
     */
    'orderStatus'?: number;
    /**
     * 宠物
     */
    'petId'?: number;
    /**
     * 服务项数量映射 { serviceId: quantity }
     */
    'serviceQuantities'?: { [key: string]: number; };
    /**
     * 开始寄养时间
     */
    'startDate'?: string;
    /**
     * 门店
     */
    'storeId'?: number;
    /**
     * 宠物主人
     */
    'userId'?: number;
}
export interface Pet {
    /**
     * 年龄
     */
    'age'?: number;
    /**
     * 宠物头像
     */
    'avatarUrl'?: string;
    /**
     * 品种
     */
    'breed'?: string;
    /**
     * 创建时间
     */
    'createTime'?: string;
    /**
     * 过往病史
     */
    'medicalHistory'?: string;
    /**
     * 宠物昵称
     */
    'name'?: string;
    /**
     * 宠物唯一id
     */
    'petId'?: number;
    /**
     * 特殊习性，如“怕生”
     */
    'specialHabits'?: string;
    /**
     * 宠物类型
     */
    'type'?: string;
    /**
     * 外键，关联用户表
     */
    'userId'?: number;
    /**
     * 疫苗接种情况（文字描述）
     */
    'vaccinationInfo'?: string;
    /**
     * 体重
     */
    'weight'?: number;
}
export interface R {
    'code'?: number;
    'data'?: object;
    'msg'?: string;
}
export interface SearchStoreDto {
    /**
     * 是否营业：1-是，0-否
     */
    'isActive'?: number;
    /**
     * 搜索关键词（可搜索门店名称或地址）
     */
    'keyword'?: string;
    /**
     * 纬度
     */
    'latitude'?: number;
    /**
     * 经度
     */
    'longitude'?: number;
}
export interface UpdateUserDto {
    /**
     * 头像地址
     */
    'avatarUrl'?: string;
    /**
     * 邮箱
     */
    'email'?: string;
    /**
     * 新密码
     */
    'newPassword'?: string;
    /**
     * 原密码
     */
    'oldPassword'?: string;
    /**
     * 手机号
     */
    'phone'?: string;
    /**
     * 用户唯一id
     */
    'userId'?: number;
    /**
     * 用户名/登录账号
     */
    'username'?: string;
}
export interface User {
    /**
     * 头像地址
     */
    'avatarUrl'?: string;
    /**
     * 创建时间
     */
    'createTime'?: string;
    /**
     * 邮箱
     */
    'email'?: string;
    /**
     * 密码
     */
    'password'?: string;
    /**
     * 手机号
     */
    'phone'?: string;
    /**
     * 外键，关联门店id
     */
    'storeId'?: number;
    /**
     * 更新时间
     */
    'updateTime'?: string;
    /**
     * 用户唯一id
     */
    'userId'?: number;
    /**
     * 用户类型：1-宠物主人，2-门店员工
     */
    'userType'?: number;
    /**
     * 用户名/登录账号
     */
    'username'?: string;
}

/**
 * BoardingOrderManagementApi - axios parameter creator
 */
export const BoardingOrderManagementApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 创建支付订单
         * @param {BoardingOrderDto} boardingOrderDto boardingOrderDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addBoardingOrderUsingPOST: async (boardingOrderDto: BoardingOrderDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'boardingOrderDto' is not null or undefined
            assertParamExists('addBoardingOrderUsingPOST', 'boardingOrderDto', boardingOrderDto)
            const localVarPath = `/boarding-order/addBoardingOrder`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(boardingOrderDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 根据订单状态和用户ID获取订单列表（支付列表）
         * @param {number} orderStatus orderStatus
         * @param {number} userId userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrderListByStatusUsingGET: async (orderStatus: number, userId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orderStatus' is not null or undefined
            assertParamExists('getOrderListByStatusUsingGET', 'orderStatus', orderStatus)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getOrderListByStatusUsingGET', 'userId', userId)
            const localVarPath = `/boarding-order/boardingOrderList`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (orderStatus !== undefined) {
                localVarQueryParameter['orderStatus'] = orderStatus;
            }

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 查询订单状态/剩余时间
         * @param {string} orderId orderId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrderStatusUsingGET: async (orderId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orderId' is not null or undefined
            assertParamExists('getOrderStatusUsingGET', 'orderId', orderId)
            const localVarPath = `/boarding-order/status/{orderId}`
                .replace(`{${"orderId"}}`, encodeURIComponent(String(orderId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BoardingOrderManagementApi - functional programming interface
 */
export const BoardingOrderManagementApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BoardingOrderManagementApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 创建支付订单
         * @param {BoardingOrderDto} boardingOrderDto boardingOrderDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addBoardingOrderUsingPOST(boardingOrderDto: BoardingOrderDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<R>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addBoardingOrderUsingPOST(boardingOrderDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BoardingOrderManagementApi.addBoardingOrderUsingPOST']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 根据订单状态和用户ID获取订单列表（支付列表）
         * @param {number} orderStatus orderStatus
         * @param {number} userId userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrderListByStatusUsingGET(orderStatus: number, userId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<R>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOrderListByStatusUsingGET(orderStatus, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BoardingOrderManagementApi.getOrderListByStatusUsingGET']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 查询订单状态/剩余时间
         * @param {string} orderId orderId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrderStatusUsingGET(orderId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<R>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOrderStatusUsingGET(orderId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BoardingOrderManagementApi.getOrderStatusUsingGET']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BoardingOrderManagementApi - factory interface
 */
export const BoardingOrderManagementApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BoardingOrderManagementApiFp(configuration)
    return {
        /**
         * 
         * @summary 创建支付订单
         * @param {BoardingOrderDto} boardingOrderDto boardingOrderDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addBoardingOrderUsingPOST(boardingOrderDto: BoardingOrderDto, options?: RawAxiosRequestConfig): AxiosPromise<R> {
            return localVarFp.addBoardingOrderUsingPOST(boardingOrderDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 根据订单状态和用户ID获取订单列表（支付列表）
         * @param {number} orderStatus orderStatus
         * @param {number} userId userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrderListByStatusUsingGET(orderStatus: number, userId: number, options?: RawAxiosRequestConfig): AxiosPromise<R> {
            return localVarFp.getOrderListByStatusUsingGET(orderStatus, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 查询订单状态/剩余时间
         * @param {string} orderId orderId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrderStatusUsingGET(orderId: string, options?: RawAxiosRequestConfig): AxiosPromise<R> {
            return localVarFp.getOrderStatusUsingGET(orderId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BoardingOrderManagementApi - object-oriented interface
 */
export class BoardingOrderManagementApi extends BaseAPI {
    /**
     * 
     * @summary 创建支付订单
     * @param {BoardingOrderDto} boardingOrderDto boardingOrderDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addBoardingOrderUsingPOST(boardingOrderDto: BoardingOrderDto, options?: RawAxiosRequestConfig) {
        return BoardingOrderManagementApiFp(this.configuration).addBoardingOrderUsingPOST(boardingOrderDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 根据订单状态和用户ID获取订单列表（支付列表）
     * @param {number} orderStatus orderStatus
     * @param {number} userId userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getOrderListByStatusUsingGET(orderStatus: number, userId: number, options?: RawAxiosRequestConfig) {
        return BoardingOrderManagementApiFp(this.configuration).getOrderListByStatusUsingGET(orderStatus, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 查询订单状态/剩余时间
     * @param {string} orderId orderId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getOrderStatusUsingGET(orderId: string, options?: RawAxiosRequestConfig) {
        return BoardingOrderManagementApiFp(this.configuration).getOrderStatusUsingGET(orderId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * FileUploadManagementApi - axios parameter creator
 */
export const FileUploadManagementApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 上传宠物头像
         * @param {File} file file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadPetAvatarUsingPOST: async (file: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'file' is not null or undefined
            assertParamExists('uploadPetAvatarUsingPOST', 'file', file)
            const localVarPath = `/upload/pet/avatar`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 上传用户头像
         * @param {File} file file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadUserAvatarUsingPOST: async (file: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'file' is not null or undefined
            assertParamExists('uploadUserAvatarUsingPOST', 'file', file)
            const localVarPath = `/upload/user/avatar`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FileUploadManagementApi - functional programming interface
 */
export const FileUploadManagementApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FileUploadManagementApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 上传宠物头像
         * @param {File} file file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadPetAvatarUsingPOST(file: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<R>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadPetAvatarUsingPOST(file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FileUploadManagementApi.uploadPetAvatarUsingPOST']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 上传用户头像
         * @param {File} file file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadUserAvatarUsingPOST(file: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<R>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadUserAvatarUsingPOST(file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FileUploadManagementApi.uploadUserAvatarUsingPOST']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FileUploadManagementApi - factory interface
 */
export const FileUploadManagementApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FileUploadManagementApiFp(configuration)
    return {
        /**
         * 
         * @summary 上传宠物头像
         * @param {File} file file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadPetAvatarUsingPOST(file: File, options?: RawAxiosRequestConfig): AxiosPromise<R> {
            return localVarFp.uploadPetAvatarUsingPOST(file, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 上传用户头像
         * @param {File} file file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadUserAvatarUsingPOST(file: File, options?: RawAxiosRequestConfig): AxiosPromise<R> {
            return localVarFp.uploadUserAvatarUsingPOST(file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FileUploadManagementApi - object-oriented interface
 */
export class FileUploadManagementApi extends BaseAPI {
    /**
     * 
     * @summary 上传宠物头像
     * @param {File} file file
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public uploadPetAvatarUsingPOST(file: File, options?: RawAxiosRequestConfig) {
        return FileUploadManagementApiFp(this.configuration).uploadPetAvatarUsingPOST(file, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 上传用户头像
     * @param {File} file file
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public uploadUserAvatarUsingPOST(file: File, options?: RawAxiosRequestConfig) {
        return FileUploadManagementApiFp(this.configuration).uploadUserAvatarUsingPOST(file, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PetManagementApi - axios parameter creator
 */
export const PetManagementApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 删除宠物
         * @param {number} petId petId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePetUsingDELETE: async (petId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'petId' is not null or undefined
            assertParamExists('deletePetUsingDELETE', 'petId', petId)
            const localVarPath = `/pet/deletePet`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (petId !== undefined) {
                localVarQueryParameter['petId'] = petId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 新增/修改宠物
         * @param {Pet} pet pet
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        savePetUsingPOST: async (pet: Pet, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pet' is not null or undefined
            assertParamExists('savePetUsingPOST', 'pet', pet)
            const localVarPath = `/pet/savePet`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pet, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PetManagementApi - functional programming interface
 */
export const PetManagementApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PetManagementApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 删除宠物
         * @param {number} petId petId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePetUsingDELETE(petId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<R>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePetUsingDELETE(petId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PetManagementApi.deletePetUsingDELETE']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 新增/修改宠物
         * @param {Pet} pet pet
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async savePetUsingPOST(pet: Pet, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<R>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.savePetUsingPOST(pet, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PetManagementApi.savePetUsingPOST']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PetManagementApi - factory interface
 */
export const PetManagementApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PetManagementApiFp(configuration)
    return {
        /**
         * 
         * @summary 删除宠物
         * @param {number} petId petId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePetUsingDELETE(petId: number, options?: RawAxiosRequestConfig): AxiosPromise<R> {
            return localVarFp.deletePetUsingDELETE(petId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 新增/修改宠物
         * @param {Pet} pet pet
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        savePetUsingPOST(pet: Pet, options?: RawAxiosRequestConfig): AxiosPromise<R> {
            return localVarFp.savePetUsingPOST(pet, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PetManagementApi - object-oriented interface
 */
export class PetManagementApi extends BaseAPI {
    /**
     * 
     * @summary 删除宠物
     * @param {number} petId petId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletePetUsingDELETE(petId: number, options?: RawAxiosRequestConfig) {
        return PetManagementApiFp(this.configuration).deletePetUsingDELETE(petId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 新增/修改宠物
     * @param {Pet} pet pet
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public savePetUsingPOST(pet: Pet, options?: RawAxiosRequestConfig) {
        return PetManagementApiFp(this.configuration).savePetUsingPOST(pet, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ServiceItemControllerApi - axios parameter creator
 */
export const ServiceItemControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取特殊需求
         * @param {number} storeId storeId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getServiceItemUsingPOST: async (storeId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'storeId' is not null or undefined
            assertParamExists('getServiceItemUsingPOST', 'storeId', storeId)
            const localVarPath = `/service-item/getServiceItem/{storeId}`
                .replace(`{${"storeId"}}`, encodeURIComponent(String(storeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ServiceItemControllerApi - functional programming interface
 */
export const ServiceItemControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ServiceItemControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 获取特殊需求
         * @param {number} storeId storeId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getServiceItemUsingPOST(storeId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<R>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getServiceItemUsingPOST(storeId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServiceItemControllerApi.getServiceItemUsingPOST']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ServiceItemControllerApi - factory interface
 */
export const ServiceItemControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ServiceItemControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary 获取特殊需求
         * @param {number} storeId storeId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getServiceItemUsingPOST(storeId: number, options?: RawAxiosRequestConfig): AxiosPromise<R> {
            return localVarFp.getServiceItemUsingPOST(storeId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ServiceItemControllerApi - object-oriented interface
 */
export class ServiceItemControllerApi extends BaseAPI {
    /**
     * 
     * @summary 获取特殊需求
     * @param {number} storeId storeId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getServiceItemUsingPOST(storeId: number, options?: RawAxiosRequestConfig) {
        return ServiceItemControllerApiFp(this.configuration).getServiceItemUsingPOST(storeId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * StoreManagementApi - axios parameter creator
 */
export const StoreManagementApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取门店详情
         * @param {number} storeId storeId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStoreByIdUsingPOST: async (storeId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'storeId' is not null or undefined
            assertParamExists('getStoreByIdUsingPOST', 'storeId', storeId)
            const localVarPath = `/store/getStoreById/{storeId}`
                .replace(`{${"storeId"}}`, encodeURIComponent(String(storeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取门店列表
         * @param {SearchStoreDto} searchStoreDto searchStoreDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStoreListUsingPOST: async (searchStoreDto: SearchStoreDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'searchStoreDto' is not null or undefined
            assertParamExists('getStoreListUsingPOST', 'searchStoreDto', searchStoreDto)
            const localVarPath = `/store/getStoreList`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(searchStoreDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StoreManagementApi - functional programming interface
 */
export const StoreManagementApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = StoreManagementApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 获取门店详情
         * @param {number} storeId storeId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStoreByIdUsingPOST(storeId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<R>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStoreByIdUsingPOST(storeId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StoreManagementApi.getStoreByIdUsingPOST']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取门店列表
         * @param {SearchStoreDto} searchStoreDto searchStoreDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStoreListUsingPOST(searchStoreDto: SearchStoreDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<R>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStoreListUsingPOST(searchStoreDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StoreManagementApi.getStoreListUsingPOST']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * StoreManagementApi - factory interface
 */
export const StoreManagementApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = StoreManagementApiFp(configuration)
    return {
        /**
         * 
         * @summary 获取门店详情
         * @param {number} storeId storeId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStoreByIdUsingPOST(storeId: number, options?: RawAxiosRequestConfig): AxiosPromise<R> {
            return localVarFp.getStoreByIdUsingPOST(storeId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取门店列表
         * @param {SearchStoreDto} searchStoreDto searchStoreDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStoreListUsingPOST(searchStoreDto: SearchStoreDto, options?: RawAxiosRequestConfig): AxiosPromise<R> {
            return localVarFp.getStoreListUsingPOST(searchStoreDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * StoreManagementApi - object-oriented interface
 */
export class StoreManagementApi extends BaseAPI {
    /**
     * 
     * @summary 获取门店详情
     * @param {number} storeId storeId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getStoreByIdUsingPOST(storeId: number, options?: RawAxiosRequestConfig) {
        return StoreManagementApiFp(this.configuration).getStoreByIdUsingPOST(storeId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取门店列表
     * @param {SearchStoreDto} searchStoreDto searchStoreDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getStoreListUsingPOST(searchStoreDto: SearchStoreDto, options?: RawAxiosRequestConfig) {
        return StoreManagementApiFp(this.configuration).getStoreListUsingPOST(searchStoreDto, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserManagementApi - axios parameter creator
 */
export const UserManagementApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 关联门店
         * @param {number} storeId storeId
         * @param {number} userId userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        associateStoreUsingPOST: async (storeId: number, userId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'storeId' is not null or undefined
            assertParamExists('associateStoreUsingPOST', 'storeId', storeId)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('associateStoreUsingPOST', 'userId', userId)
            const localVarPath = `/user/associateStore`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (storeId !== undefined) {
                localVarQueryParameter['storeId'] = storeId;
            }

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取用户详情
         * @param {number} userId userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserDetailUsingPOST: async (userId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserDetailUsingPOST', 'userId', userId)
            const localVarPath = `/user/getUserDetail/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 登录
         * @param {string} password password
         * @param {string} username username
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginUsingPOST: async (password: string, username: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'password' is not null or undefined
            assertParamExists('loginUsingPOST', 'password', password)
            // verify required parameter 'username' is not null or undefined
            assertParamExists('loginUsingPOST', 'username', username)
            const localVarPath = `/user/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (password !== undefined) {
                localVarQueryParameter['password'] = password;
            }

            if (username !== undefined) {
                localVarQueryParameter['username'] = username;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 注册
         * @param {User} user user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUsingPOST: async (user: User, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'user' is not null or undefined
            assertParamExists('registerUsingPOST', 'user', user)
            const localVarPath = `/user/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(user, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 修改用户
         * @param {UpdateUserDto} updateUserDto updateUserDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserUsingPOST: async (updateUserDto: UpdateUserDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateUserDto' is not null or undefined
            assertParamExists('updateUserUsingPOST', 'updateUserDto', updateUserDto)
            const localVarPath = `/user/updateUser`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateUserDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserManagementApi - functional programming interface
 */
export const UserManagementApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserManagementApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 关联门店
         * @param {number} storeId storeId
         * @param {number} userId userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async associateStoreUsingPOST(storeId: number, userId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<R>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.associateStoreUsingPOST(storeId, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserManagementApi.associateStoreUsingPOST']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取用户详情
         * @param {number} userId userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserDetailUsingPOST(userId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<R>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserDetailUsingPOST(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserManagementApi.getUserDetailUsingPOST']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 登录
         * @param {string} password password
         * @param {string} username username
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginUsingPOST(password: string, username: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<R>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginUsingPOST(password, username, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserManagementApi.loginUsingPOST']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 注册
         * @param {User} user user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerUsingPOST(user: User, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<R>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerUsingPOST(user, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserManagementApi.registerUsingPOST']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 修改用户
         * @param {UpdateUserDto} updateUserDto updateUserDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateUserUsingPOST(updateUserDto: UpdateUserDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<R>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateUserUsingPOST(updateUserDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserManagementApi.updateUserUsingPOST']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserManagementApi - factory interface
 */
export const UserManagementApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserManagementApiFp(configuration)
    return {
        /**
         * 
         * @summary 关联门店
         * @param {number} storeId storeId
         * @param {number} userId userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        associateStoreUsingPOST(storeId: number, userId: number, options?: RawAxiosRequestConfig): AxiosPromise<R> {
            return localVarFp.associateStoreUsingPOST(storeId, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取用户详情
         * @param {number} userId userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserDetailUsingPOST(userId: number, options?: RawAxiosRequestConfig): AxiosPromise<R> {
            return localVarFp.getUserDetailUsingPOST(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 登录
         * @param {string} password password
         * @param {string} username username
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginUsingPOST(password: string, username: string, options?: RawAxiosRequestConfig): AxiosPromise<R> {
            return localVarFp.loginUsingPOST(password, username, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 注册
         * @param {User} user user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUsingPOST(user: User, options?: RawAxiosRequestConfig): AxiosPromise<R> {
            return localVarFp.registerUsingPOST(user, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 修改用户
         * @param {UpdateUserDto} updateUserDto updateUserDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserUsingPOST(updateUserDto: UpdateUserDto, options?: RawAxiosRequestConfig): AxiosPromise<R> {
            return localVarFp.updateUserUsingPOST(updateUserDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserManagementApi - object-oriented interface
 */
export class UserManagementApi extends BaseAPI {
    /**
     * 
     * @summary 关联门店
     * @param {number} storeId storeId
     * @param {number} userId userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public associateStoreUsingPOST(storeId: number, userId: number, options?: RawAxiosRequestConfig) {
        return UserManagementApiFp(this.configuration).associateStoreUsingPOST(storeId, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取用户详情
     * @param {number} userId userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getUserDetailUsingPOST(userId: number, options?: RawAxiosRequestConfig) {
        return UserManagementApiFp(this.configuration).getUserDetailUsingPOST(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 登录
     * @param {string} password password
     * @param {string} username username
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public loginUsingPOST(password: string, username: string, options?: RawAxiosRequestConfig) {
        return UserManagementApiFp(this.configuration).loginUsingPOST(password, username, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 注册
     * @param {User} user user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public registerUsingPOST(user: User, options?: RawAxiosRequestConfig) {
        return UserManagementApiFp(this.configuration).registerUsingPOST(user, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 修改用户
     * @param {UpdateUserDto} updateUserDto updateUserDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateUserUsingPOST(updateUserDto: UpdateUserDto, options?: RawAxiosRequestConfig) {
        return UserManagementApiFp(this.configuration).updateUserUsingPOST(updateUserDto, options).then((request) => request(this.axios, this.basePath));
    }
}



