/* tslint:disable */
/* eslint-disable */
/**
 * 宠物寄养平台
 * 宠物寄养平台
 *
 * The version of the OpenAPI document: 1.0
 * Contact: 123456@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

